### ISSUE TITLE
Cannot compile example project with Xcode 13

### ISSUE THREAD

**Issue by alicerunsonfedora** [kelvin13/godot-swift#4]
I wanted to try this package out for myself, so I tried to clone the example project and follow the tutorial. However, it seems that I can't get the product to build with Xcode 13 which includes Swift 5.5.

```
error: failed to compile package plugin:
[...] (Redacted)

/Users/marquis/Developer/godot-swift/sources/godot-nativescript/main.swift:1:8: error: no such module 'PackagePlugin'
import PackagePlugin
       ^
```

Is there something I'm missing?

**Update**:

- Tried switching the toolchain over to the snapshot `swift-5.5-DEVELOPMENT-SNAPSHOT-2021-07-29-a-osx`
- Tried switching to Command Line Tools only

I'm running the latest Monterey dev beta (21A5294g)

**Comment by alicerunsonfedora** [comment]
I've found a workaround for this issue, so I'll close it (though I am also running into #3).

I've simply ran `export TOOLCHAINS=swift` to point to the development snapshot before running the other commands. Maybe this should be included in the documentation, for those unfamiliar with working with those snapshots and not using `swiftenv`?
